# https://github.com/kubernetes/ingress-nginx/blob/main/charts/ingress-nginx/values.yaml
---
controller:
  ingressClassResource:
    default: "true"

  service:
    annotations:
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      service.beta.kubernetes.io/aws-load-balancer-cross-zone-load-balancing-enabled: "true"
      service.beta.kubernetes.io/aws-load-balancer-type: nlb-ip

  resources:
    limits:
      cpu: "500m"
      memory: "512Mi"
    requests:
      cpu: "150m"
      memory: "200Mi"
